apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component:  shipping
    tier: backend
data:
  CART_ENDPOINT: "cart:8080" 
  DB_HOST: "mysql"
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component:  shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project:  roboshop
      component: shipping
      tier: backend
  template:
    metadata:
      labels: 
        project: roboshop
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image:  anjuma11/shipping:v1
      envFrom:
      - configMapRef:
          name: shipping
---

apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  selector:
    project: roboshop
    component: shipping
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

