apiVersion: v1
kind: Secrete
metadata:
  name: mysql
  labels:
    component: mysql
    project: roboshop
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: database
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mysql
        image: anjuma11/mysql:v1
        envFrom:
        - secretRef:
            name: mysql
---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: mysql
    tier: database
spec:
  selector:
    project: roboshop
    component: mysql
    tier: database
  ports:
  - protocol: tcp
    port: 3306
    target-port: 3306
  
