apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component:  user
    tier: backend
data:
  MONGO_URL: "mongodb://mongodb:27017/users" 
  REDIS_URL: "redis://redis:6379" 
  MONGO: "true"
---  

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component:  user
    tier: backend
sepc:
  replicas: 1
  selector:
    matchLables:
      project:  roboshop
      component: user
      tier: backend
  template:
    metadata:
      labels: 
        project: roboshop
        component: user
        tier: backend
    spec:
      containers:
      - name: user
        image:  anjuma11/user:v1
        envFrom:
        - configMapRef:
            name: user
---

apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  selectors:
    project: roboshop
    component: user
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

